version: '3.8'

services:
  fund-stack-api:
    build: .
    image: fund-stack-api
    container_name: fund-stack-api
    ports:
      - "8000:8000"
    volumes:
      - ./session.json:/app/session.json
